@baseUrl=http://localhost:8787/movements

# (name, difficulty, description, extraNotes)

### create new movement
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "test",
  "difficulty": 1,
  "description": "testing",
  "extraNotes": "test"
}

### get movements
GET {{baseUrl}}